file_list:
  - src/*.vhd
rule:
  constant_004: # names
    case: upper
  constant_015: # prefix
    disable: false
    prefixes: ["C_"]
  generic_020: # prefix
    disable: false
  port_010: # names
    case: lower
  port_011: # prefix
    disable: false
    prefixes: ["i", "o"]
  instantiation_011: # names
    case: lower
  signal_007: # default initialization
    disable: true
  subtype_004: # prefix
    disable: false
  type_015: # prefix
    disable: false
